/**
 * DEMO lots for development and design review only (`pnpm seed --demo`).
 * SKUs start with DEMO- so they are easy to find and delete before launch.
 * Prices are placeholders, not trade prices.
 */
import type { PriceUnit } from '../src/lib/pricing'

export type DemoLot = {
  sku: string
  title: string
  section: number
  subcategories: string[]
  styles: string[]
  brands: [string, number][]
  collection?: string
  descriptors: [string, string][]
  bestFor: string[]
  lotType: 'single-brand' | 'mixed-brand' | 'bale-kg' | 'shape-specific'
  pieces?: number
  weightKg?: number
  grade: 'cream' | 'a' | 'b' | 'mixed'
  era?: 'verified-vintage' | '1980s' | '1990s' | 'verified-y2k' | 'y2k-style' | 'modern'
  division: ('womens' | 'mens' | 'unisex')[]
  price?: number
  unit: PriceUnit
  priceVisibility: 'public' | 'trade-only' | 'on-request'
  lotsAvailable: number
  stock: 'in-stock' | 'low' | 'arriving' | 'sold'
  badges: ('new' | 'best-seller' | 'verified-era')[]
  ageDays: number
}

const CP = 'Classic & Preppy'
const SP = 'Sportswear & Activewear'
const OT = 'Outdoor & Technical / Gorpcore'
const WU = 'Workwear & Utility'
const ST = 'Streetwear'
const DN = 'Denimwear'
const YV = 'Y2K & Vintage'
const FW = 'Sports Fanwear & Official Merchandise'

let n = 0
const lot = (l: Omit<DemoLot, 'sku'>): DemoLot => ({ ...l, sku: `DEMO-${String(++n).padStart(3, '0')}` })

export function buildDemoLots(): DemoLot[] {
  n = 0
  return [
    lot({ title: '25x The North Face Puffer Jackets — Premium Nuptse / Baltoro', section: 13, subcategories: ['Classic / Short Puffer Jackets'], styles: [OT, ST], brands: [['The North Face', 25]], collection: 'TNF Puffers — Premium / Iconic / Vintage Era', descriptors: [['Insulation', 'Down'], ['Fill power', '700 Fill'], ['Hood', 'Hooded'], ['Construction', 'Baffled']], bestFor: ['Streetwear resellers', 'Specialist TNF buyers'], lotType: 'single-brand', pieces: 25, weightKg: 22, grade: 'a', era: '1990s', division: ['unisex'], price: 1450, unit: 'lot', priceVisibility: 'trade-only', lotsAvailable: 2, stock: 'low', badges: ['best-seller', 'verified-era'], ageDays: 2 }),
    lot({ title: '50x The North Face Puffer Jackets — Core 550–650 Fill', section: 13, subcategories: ['Classic / Short Puffer Jackets'], styles: [OT], brands: [['The North Face', 50]], collection: 'TNF Puffers — Core', descriptors: [['Insulation', 'Down'], ['Fill power', '600 Fill'], ['Length', 'Hip-Length']], bestFor: ['General branded resellers', 'Online & live sellers'], lotType: 'single-brand', pieces: 50, weightKg: 41, grade: 'a', era: 'modern', division: ['mens', 'womens'], price: 1650, unit: 'lot', priceVisibility: 'public', lotsAvailable: 6, stock: 'in-stock', badges: ['new'], ageDays: 1 }),
    lot({ title: '40x The North Face Standard & Synthetic Puffers', section: 13, subcategories: ['Lightweight / Packable Puffer Jackets'], styles: [OT], brands: [['The North Face', 40]], collection: 'TNF Puffers — Standard', descriptors: [['Insulation', 'Synthetic'], ['Fill power', '500 Fill']], bestFor: ['Budget resellers', 'Volume-focused sellers'], lotType: 'single-brand', pieces: 40, weightKg: 30, grade: 'b', era: 'modern', division: ['unisex'], price: 980, unit: 'lot', priceVisibility: 'public', lotsAvailable: 9, stock: 'in-stock', badges: [], ageDays: 8 }),
    lot({ title: '20x Branded Long Puffer Coats & Parkas — Mixed', section: 13, subcategories: ['Long Puffer Coats / Puffer Parkas'], styles: [OT, SP], brands: [['The North Face', 8], ['Columbia', 6], ['Nike', 3], ['Patagonia', 3]], descriptors: [['Length', 'Knee-Length'], ['Insulation', 'Down']], bestFor: ['Women-focused resellers', 'Premium winterwear sellers'], lotType: 'mixed-brand', pieces: 20, weightKg: 24, grade: 'a', division: ['womens'], price: 890, unit: 'lot', priceVisibility: 'public', lotsAvailable: 3, stock: 'in-stock', badges: [], ageDays: 12 }),
    lot({ title: '30x Carhartt Detroit & Active Work Jackets', section: 12, subcategories: ['Heavy Workwear / Duck-Canvas Jackets'], styles: [WU, ST], brands: [['Carhartt', 30]], collection: 'Carhartt Detroit / Active / Chore Jackets', descriptors: [['Material / fabric technology', 'Duck Canvas'], ['Hood', 'Hooded']], bestFor: ['Streetwear resellers', 'Workwear resellers'], lotType: 'single-brand', pieces: 30, weightKg: 42, grade: 'a', era: '1990s', division: ['mens'], price: 1320, unit: 'lot', priceVisibility: 'public', lotsAvailable: 4, stock: 'in-stock', badges: ['best-seller'], ageDays: 5 }),
    lot({ title: '40x Dickies Eisenhower & Work Jackets', section: 12, subcategories: ['Lightweight Work / Utility Jackets'], styles: [WU], brands: [['Dickies', 40]], collection: 'Dickies Eisenhower Jackets', descriptors: [['Construction / design', 'Lined']], bestFor: ['Workwear resellers', 'Vintage shops'], lotType: 'single-brand', pieces: 40, weightKg: 34, grade: 'a', division: ['mens'], price: 720, unit: 'lot', priceVisibility: 'public', lotsAvailable: 5, stock: 'in-stock', badges: [], ageDays: 20 }),
    lot({ title: '35x Windbreakers — Nike, Adidas, Columbia Mix', section: 12, subcategories: ['Windbreakers'], styles: [SP, OT], brands: [['Nike', 14], ['Adidas', 11], ['Columbia', 10]], descriptors: [['Material / fabric technology', 'Nylon'], ['Weather protection', 'Wind-Resistant'], ['Construction / design', 'Colour-Block']], bestFor: ['Streetwear resellers', 'Online & live sellers'], lotType: 'mixed-brand', pieces: 35, weightKg: 14, grade: 'a', era: '1990s', division: ['unisex'], price: 540, unit: 'lot', priceVisibility: 'public', lotsAvailable: 7, stock: 'in-stock', badges: ['new'], ageDays: 3 }),
    lot({ title: '25x Columbia Bugaboo / Whirlibird 3-in-1 Jackets', section: 12, subcategories: ['3-in-1 / Removable-Liner Jackets'], styles: [OT], brands: [['Columbia', 25]], collection: 'Columbia Bugaboo / Whirlibird 3-in-1', descriptors: [['Weather protection', 'Waterproof'], ['Use / style', 'Technical']], bestFor: ['Gorpcore resellers', 'Outdoor & technical resellers'], lotType: 'single-brand', pieces: 25, weightKg: 26, grade: 'a', division: ['mens'], price: 690, unit: 'lot', priceVisibility: 'public', lotsAvailable: 3, stock: 'in-stock', badges: [], ageDays: 15 }),
    lot({ title: '30x Branded Puffer Gilets — TNF, Nike, Ralph Lauren', section: 12, subcategories: ['Puffer Gilets / Puffer Vests'], styles: [OT, CP], brands: [['The North Face', 12], ['Nike', 10], ['Ralph Lauren', 8]], descriptors: [['Construction / design', 'Diamond-Quilt']], bestFor: ['Transitional-season sellers', 'General branded resellers'], lotType: 'mixed-brand', pieces: 30, weightKg: 15, grade: 'a', division: ['unisex'], price: 610, unit: 'lot', priceVisibility: 'public', lotsAvailable: 4, stock: 'in-stock', badges: [], ageDays: 25 }),
    lot({ title: '30x Patagonia Retro-X / Synchilla / Snap-T Fleece', section: 11, subcategories: ['Sherpa / High-Pile Fleece', 'Classic / Polar Fleece'], styles: [OT], brands: [['Patagonia', 30]], collection: 'Patagonia Retro-X / Retro Pile / Synchilla', descriptors: [['Zip', 'Snap Placket'], ['Design group', 'Colour-Block']], bestFor: ['Gorpcore resellers', 'Vintage shops'], lotType: 'single-brand', pieces: 30, weightKg: 18, grade: 'a', era: '1990s', division: ['unisex'], price: 1180, unit: 'lot', priceVisibility: 'public', lotsAvailable: 2, stock: 'low', badges: ['verified-era'], ageDays: 4 }),
    lot({ title: '40x The North Face Denali Fleece Jackets', section: 11, subcategories: ['Technical / Performance Fleece', 'Panelled / Hybrid Fleece'], styles: [OT], brands: [['The North Face', 40]], collection: 'TNF Denali Fleece', descriptors: [['Zip', 'Full-Zip'], ['Design group', 'Colour-Block']], bestFor: ['Gorpcore resellers', 'Streetwear resellers'], lotType: 'single-brand', pieces: 40, weightKg: 26, grade: 'a', division: ['unisex'], price: 1090, unit: 'lot', priceVisibility: 'public', lotsAvailable: 5, stock: 'in-stock', badges: ['best-seller'], ageDays: 9 }),
    lot({ title: '50x Mixed Brand Crazy Pattern Fleece', section: 11, subcategories: ['Classic / Polar Fleece'], styles: [YV, OT], brands: [['Mix Brand / Unbranded', 50]], descriptors: [['Design group', 'Crazy'], ['Design group', 'Southwestern']], bestFor: ['Vintage shops', 'Y2K boutiques'], lotType: 'mixed-brand', pieces: 50, weightKg: 28, grade: 'b', era: 'y2k-style', division: ['unisex'], price: 420, unit: 'lot', priceVisibility: 'public', lotsAvailable: 11, stock: 'in-stock', badges: [], ageDays: 30 }),
    lot({ title: '40x Adidas Firebird / SST Track Jackets', section: 10, subcategories: ['Classic Track Jackets'], styles: [SP, ST], brands: [['Adidas', 40]], collection: 'Adidas Firebird / SST / Beckenbauer', descriptors: [['Design group', 'Stripe-Detail'], ['Fabric', 'Polyester Tricot']], bestFor: ['Streetwear resellers', 'Online & live sellers'], lotType: 'single-brand', pieces: 40, weightKg: 17, grade: 'a', division: ['unisex'], price: 760, unit: 'lot', priceVisibility: 'public', lotsAvailable: 6, stock: 'in-stock', badges: ['new', 'best-seller'], ageDays: 1 }),
    lot({ title: '30x Official Football Club Track Jackets — Mixed Clubs', section: 10, subcategories: ['Official Football Club Track Jackets'], styles: [SP, FW], brands: [['Adidas', 12], ['Nike', 10], ['Umbro', 4], ['Kappa', 4]], descriptors: [['Design group', 'Chest Logo']], bestFor: ['Sports fanwear sellers', 'Streetwear resellers'], lotType: 'mixed-brand', pieces: 30, weightKg: 12, grade: 'a', era: '1990s', division: ['mens'], price: 580, unit: 'lot', priceVisibility: 'public', lotsAvailable: 3, stock: 'in-stock', badges: ['verified-era'], ageDays: 11 }),
    lot({ title: '25x Juicy Couture Velour Track Jackets', section: 10, subcategories: ['Velour Track Jackets'], styles: [YV], brands: [['Juicy Couture', 25]], descriptors: [['Fabric', 'Velour']], bestFor: ['Y2K boutiques', 'Y2K & McBling resellers'], lotType: 'single-brand', pieces: 25, weightKg: 9, grade: 'a', era: 'verified-y2k', division: ['womens'], price: 520, unit: 'lot', priceVisibility: 'public', lotsAvailable: 2, stock: 'low', badges: ['verified-era'], ageDays: 6 }),
    lot({ title: '50x Ralph Lauren Cable-Knit & Crewneck Jumpers', section: 9, subcategories: ['Classic Crewneck / Round-Neck Sweaters'], styles: [CP], brands: [['Ralph Lauren', 50]], descriptors: [['Knit construction', 'Cable-Knit'], ['Fibre', 'Cotton'], ['Heritage / preppy', 'Preppy']], bestFor: ['Vintage shops', 'Premium branded resellers'], lotType: 'single-brand', pieces: 50, weightKg: 27, grade: 'a', division: ['mens', 'womens'], price: 1240, unit: 'lot', priceVisibility: 'public', lotsAvailable: 4, stock: 'in-stock', badges: ['best-seller'], ageDays: 7 }),
    lot({ title: '40x Quarter-Zip Knits — Tommy, Lacoste, GANT', section: 9, subcategories: ['Half-Zip / Quarter-Zip Sweaters'], styles: [CP], brands: [['Tommy Hilfiger', 16], ['Lacoste', 14], ['GANT', 10]], descriptors: [['Garment weight', 'Midweight']], bestFor: ['Vintage shops', 'General branded resellers'], lotType: 'mixed-brand', pieces: 40, weightKg: 19, grade: 'a', division: ['mens'], price: 780, unit: 'lot', priceVisibility: 'public', lotsAvailable: 5, stock: 'in-stock', badges: [], ageDays: 14 }),
    lot({ title: '60x Fair Isle / Nordic Knitwear — Unbranded Vintage', section: 9, subcategories: ['Classic Crewneck / Round-Neck Sweaters', 'Classic / Button-Front Cardigans'], styles: [YV], brands: [['Unbranded Y2K', 60]], descriptors: [['Pattern / colour', 'Fair Isle'], ['Pattern / colour', 'Nordic'], ['Heritage / preppy', 'Grandpa']], bestFor: ['Vintage shops', 'Style-led resellers'], lotType: 'mixed-brand', pieces: 60, weightKg: 30, grade: 'b', era: 'verified-vintage', division: ['unisex'], price: 460, unit: 'lot', priceVisibility: 'public', lotsAvailable: 8, stock: 'in-stock', badges: [], ageDays: 21 }),
    lot({ title: '50x Nike & Adidas Spellout Sweatshirts', section: 8, subcategories: ['Crewneck / Round-Neck Sweatshirts'], styles: [SP, ST], brands: [['Nike', 28], ['Adidas', 22]], descriptors: [['Design group', 'Spellout']], bestFor: ['Streetwear resellers', 'Online & live sellers'], lotType: 'mixed-brand', pieces: 50, weightKg: 29, grade: 'a', era: '1990s', division: ['unisex'], price: 890, unit: 'lot', priceVisibility: 'public', lotsAvailable: 7, stock: 'in-stock', badges: ['best-seller', 'verified-era'], ageDays: 2 }),
    lot({ title: '60x College & University Hoodies', section: 8, subcategories: ['Pullover / Overhead Hoodies'], styles: [FW, ST], brands: [['Graphic Design', 60]], descriptors: [['Graphic theme', 'University / College'], ['Design group', 'Graphic / Printed']], bestFor: ['Vintage shops', 'Online & live sellers'], lotType: 'mixed-brand', pieces: 60, weightKg: 38, grade: 'a', division: ['unisex'], price: 640, unit: 'lot', priceVisibility: 'public', lotsAvailable: 10, stock: 'in-stock', badges: [], ageDays: 18 }),
    lot({ title: '40x Carhartt Logo Hoodies', section: 8, subcategories: ['Pullover / Overhead Hoodies', 'Zip-Up / Full-Zip Hoodies'], styles: [WU, ST], brands: [['Carhartt', 40]], descriptors: [['Design group', 'Chest Logo / Small Logo']], bestFor: ['Streetwear resellers', 'Workwear resellers'], lotType: 'single-brand', pieces: 40, weightKg: 28, grade: 'a', division: ['mens'], price: 820, unit: 'lot', priceVisibility: 'public', lotsAvailable: 0, stock: 'sold', badges: [], ageDays: 40 }),
    lot({ title: '30x True Religion Big T / Super T Jeans', section: 7, subcategories: ['Bootcut / Flared Jeans', 'Regular / Straight Jeans'], styles: [DN, YV], brands: [['True Religion', 30]], collection: 'True Religion Big T / Super T', descriptors: [['Embellishment', 'Big T / Super T Stitch'], ['Embellishment', 'Horseshoe Pockets']], bestFor: ['Y2K boutiques', 'Streetwear resellers'], lotType: 'single-brand', pieces: 30, weightKg: 21, grade: 'a', era: 'verified-y2k', division: ['mens', 'womens'], price: 980, unit: 'lot', priceVisibility: 'public', lotsAvailable: 3, stock: 'in-stock', badges: ['new', 'verified-era'], ageDays: 1 }),
    lot({ title: '30x Miss Me & Rock Revival Embellished Jeans', section: 7, subcategories: ['Statement / Embellished / Embroidered / Rhinestoned / Studded Jeans'], styles: [DN, YV], brands: [['Miss Me', 16], ['Rock Revival', 14]], descriptors: [['Embellishment', 'Rhinestone'], ['Embellishment', 'Fleur-de-Lis'], ['Rise', 'Low-Rise']], bestFor: ['Y2K boutiques', 'Y2K & McBling resellers'], lotType: 'mixed-brand', pieces: 30, weightKg: 20, grade: 'a', era: 'y2k-style', division: ['womens'], price: 870, unit: 'lot', priceVisibility: 'public', lotsAvailable: 4, stock: 'in-stock', badges: ['best-seller'], ageDays: 5 }),
    lot({ title: "50x Levi's 501 / 505 Straight Jeans", section: 7, subcategories: ['Regular / Straight Jeans'], styles: [DN], brands: [["Levi's", 50]], collection: "Levi's 501 / 505 Straight", descriptors: [['Fit', 'Straight'], ['Wash', 'Medium Wash']], bestFor: ['Vintage shops', 'Online & live sellers'], lotType: 'single-brand', pieces: 50, weightKg: 34, grade: 'a', division: ['mens'], price: 940, unit: 'lot', priceVisibility: 'public', lotsAvailable: 8, stock: 'in-stock', badges: [], ageDays: 10 }),
    lot({ title: '40x Baggy Hip-Hop Jeans — Southpole, FUBU, Rocawear', section: 7, subcategories: ['Baggy / Wide-Leg / Hip-Hop / Skate Jeans'], styles: [ST, YV], brands: [['Southpole', 15], ['FUBU', 13], ['Rocawear', 12]], descriptors: [['Fit', 'Baggy / Wide-Leg']], bestFor: ['Streetwear resellers', 'Y2K boutiques'], lotType: 'mixed-brand', pieces: 40, weightKg: 30, grade: 'a', era: 'verified-y2k', division: ['mens'], price: 690, unit: 'lot', priceVisibility: 'public', lotsAvailable: 5, stock: 'in-stock', badges: ['verified-era'], ageDays: 16 }),
    lot({ title: '40x Carhartt Double-Knee & Carpenter Pants', section: 6, subcategories: ['Double-Knee / Reinforced Work Pants', 'Carpenter / Painter / Utility / Workwear Pants'], styles: [WU, ST], brands: [['Carhartt', 40]], collection: 'Carhartt Double-Knee / Carpenter Pants', descriptors: [['Fabric', 'Duck Canvas'], ['Fit', 'Loose / Baggy']], bestFor: ['Streetwear resellers', 'Workwear resellers'], lotType: 'single-brand', pieces: 40, weightKg: 32, grade: 'a', division: ['mens'], price: 1080, unit: 'lot', priceVisibility: 'public', lotsAvailable: 3, stock: 'in-stock', badges: ['best-seller'], ageDays: 3 }),
    lot({ title: '50x Dickies 874 Work Pants', section: 6, subcategories: ['Carpenter / Painter / Utility / Workwear Pants'], styles: [WU], brands: [['Dickies', 50]], collection: 'Dickies 874 / Double-Knee Work Pants', descriptors: [['Fabric', 'Twill']], bestFor: ['Workwear resellers', 'Online & live sellers'], lotType: 'single-brand', pieces: 50, weightKg: 30, grade: 'a', division: ['mens'], price: 640, unit: 'lot', priceVisibility: 'public', lotsAvailable: 9, stock: 'in-stock', badges: [], ageDays: 22 }),
    lot({ title: '60x Track Pants — Adidas & Nike', section: 6, subcategories: ['Track Pants'], styles: [SP], brands: [['Adidas', 34], ['Nike', 26]], descriptors: [['Fabric', 'Polyester Tricot']], bestFor: ['Streetwear resellers', 'Market traders'], lotType: 'mixed-brand', pieces: 60, weightKg: 21, grade: 'a', division: ['unisex'], price: 720, unit: 'lot', priceVisibility: 'public', lotsAvailable: 6, stock: 'in-stock', badges: ['new'], ageDays: 2 }),
    lot({ title: '100x Branded Shorts Mix — Sports & Chino', section: 5, subcategories: ['Athletic / Activewear / Training / Gym Shorts', 'Chino / Smart Casual Shorts'], styles: [SP, CP], brands: [['Nike', 30], ['Adidas', 25], ['Ralph Lauren', 20], ['Tommy Hilfiger', 25]], descriptors: [], bestFor: ['Market traders', 'Volume-focused sellers'], lotType: 'mixed-brand', pieces: 100, weightKg: 25, grade: 'b', division: ['unisex'], price: 520, unit: 'lot', priceVisibility: 'public', lotsAvailable: 12, stock: 'in-stock', badges: [], ageDays: 35 }),
    lot({ title: '40x Y2K Embellished Denim Shorts', section: 5, subcategories: ["Women's Y2K Denim Shorts — Embellished / Embroidered / Rhinestoned"], styles: [DN, YV], brands: [['Miss Me', 20], ['Rock Revival', 10], ['True Religion', 10]], descriptors: [['Embellishment', 'Rhinestone']], bestFor: ['Y2K boutiques', 'Women-focused resellers'], lotType: 'mixed-brand', pieces: 40, weightKg: 11, grade: 'a', era: 'y2k-style', division: ['womens'], price: 560, unit: 'lot', priceVisibility: 'public', lotsAvailable: 4, stock: 'in-stock', badges: [], ageDays: 13 }),
    lot({ title: '60x Flannel & Checked Shirts — Mixed Brands', section: 4, subcategories: ['Flannel / Checked / Plaid / Buffalo Check / Tartan Shirts'], styles: [OT, WU], brands: [['Columbia', 15], ['L.L.Bean', 12], ['Carhartt', 10], ['Unbranded', 23]], descriptors: [['Print / pattern', 'Check / Plaid'], ['Sleeve', 'Long Sleeve']], bestFor: ['Vintage shops', 'Market traders'], lotType: 'mixed-brand', pieces: 60, weightKg: 24, grade: 'a', division: ['mens'], price: 480, unit: 'lot', priceVisibility: 'public', lotsAvailable: 10, stock: 'in-stock', badges: [], ageDays: 19 }),
    lot({ title: '50x Ralph Lauren Oxford Shirts', section: 4, subcategories: ['Classic / Casual / Button-Up / Button-Down Shirts'], styles: [CP], brands: [['Ralph Lauren', 50]], descriptors: [['Print / pattern', 'Solid'], ['Print / pattern', 'Vertical Stripe']], bestFor: ['Vintage shops', 'Premium branded resellers'], lotType: 'single-brand', pieces: 50, weightKg: 16, grade: 'a', division: ['mens'], price: 760, unit: 'lot', priceVisibility: 'public', lotsAvailable: 5, stock: 'in-stock', badges: [], ageDays: 17 }),
    lot({ title: '40x Striped Rugby Shirts — Ralph Lauren, GANT, Tommy', section: 3, subcategories: ['Classic Striped Rugby Shirts'], styles: [CP], brands: [['Ralph Lauren', 18], ['GANT', 12], ['Tommy Hilfiger', 10]], descriptors: [], bestFor: ['Vintage shops', 'Style-led resellers'], lotType: 'mixed-brand', pieces: 40, weightKg: 26, grade: 'a', era: '1990s', division: ['mens'], price: 860, unit: 'lot', priceVisibility: 'public', lotsAvailable: 3, stock: 'in-stock', badges: ['verified-era'], ageDays: 8 }),
    lot({ title: '50x Ralph Lauren Big Pony Polos', section: 2, subcategories: ['Classic / Piqué Polos'], styles: [CP, ST], brands: [['Ralph Lauren', 50]], collection: 'Ralph Lauren Big Pony / Statement Polos', descriptors: [['Logo size', 'Large / Statement Logo']], bestFor: ['Streetwear resellers', 'Online & live sellers'], lotType: 'single-brand', pieces: 50, weightKg: 13, grade: 'a', division: ['mens'], price: 820, unit: 'lot', priceVisibility: 'public', lotsAvailable: 6, stock: 'in-stock', badges: ['best-seller'], ageDays: 4 }),
    lot({ title: '60x Lacoste Classic Piqué Polos', section: 2, subcategories: ['Classic / Piqué Polos'], styles: [CP], brands: [['Lacoste', 60]], descriptors: [['Logo size', 'Small Logo']], bestFor: ['General branded resellers', 'Online & live sellers'], lotType: 'single-brand', pieces: 60, weightKg: 15, grade: 'a', division: ['mens', 'womens'], price: 780, unit: 'lot', priceVisibility: 'public', lotsAvailable: 7, stock: 'in-stock', badges: [], ageDays: 12 }),
    lot({ title: '100x Single Stitch & Vintage Graphic Tees', section: 1, subcategories: ['Single Stitch Tees', 'Vintage Tees'], styles: [YV, ST], brands: [['Unbranded', 100]], descriptors: [['Design group', 'Graphic']], bestFor: ['Vintage shops', 'Online & live sellers'], lotType: 'mixed-brand', pieces: 100, weightKg: 18, grade: 'b', era: 'verified-vintage', division: ['unisex'], price: 650, unit: 'lot', priceVisibility: 'public', lotsAvailable: 5, stock: 'in-stock', badges: ['verified-era'], ageDays: 6 }),
    lot({ title: '60x Football & Basketball Jerseys — Nike / Adidas', section: 1, subcategories: ['Football / Basketball Jerseys'], styles: [SP, FW], brands: [['Nike', 30], ['Adidas', 30]], descriptors: [], bestFor: ['Sports fanwear sellers', 'Streetwear resellers'], lotType: 'mixed-brand', pieces: 60, weightKg: 12, grade: 'a', era: '1990s', division: ['mens'], price: 940, unit: 'lot', priceVisibility: 'public', lotsAvailable: 2, stock: 'low', badges: ['new'], ageDays: 1 }),
    lot({ title: 'T-Shirt Bale by kg — Branded Mix, 45 kg', section: 1, subcategories: ['Branded / Logo T-Shirts'], styles: [SP, CP], brands: [['Nike', 40], ['Adidas', 35], ['Ralph Lauren', 25], ['Tommy Hilfiger', 20]], descriptors: [], bestFor: ['Market traders', 'Volume-focused sellers'], lotType: 'bale-kg', pieces: 180, weightKg: 45, grade: 'b', division: ['unisex'], price: 7.5, unit: 'kg', priceVisibility: 'public', lotsAvailable: 14, stock: 'in-stock', badges: [], ageDays: 9 }),
    lot({ title: '40x Lululemon Align & Wunder Train Leggings', section: 14, subcategories: ['Leggings / Yoga Pants / Training & Running Tights'], styles: [SP], brands: [['Lululemon', 40]], collection: 'Lululemon Align', descriptors: [['Use', 'Yoga / Studio'], ['Fabric', 'Nulu / Buttery-Soft']], bestFor: ['Activewear specialists', "Women's athleisure sellers"], lotType: 'single-brand', pieces: 40, weightKg: 7, grade: 'cream', division: ['womens'], price: 1180, unit: 'lot', priceVisibility: 'trade-only', lotsAvailable: 3, stock: 'in-stock', badges: ['best-seller'], ageDays: 3 }),
    lot({ title: '25x Lululemon Define & Scuba Jackets', section: 14, subcategories: ['Fitted Studio / Training / Running Jackets', 'Pullover / Full-Zip Hoodies'], styles: [SP], brands: [['Lululemon', 25]], collection: 'Lululemon Define', descriptors: [['Fabric', 'Scuba / Cotton Fleece']], bestFor: ['Activewear specialists', 'Online & live sellers'], lotType: 'single-brand', pieces: 25, weightKg: 9, grade: 'a', division: ['womens'], price: 1050, unit: 'lot', priceVisibility: 'public', lotsAvailable: 2, stock: 'low', badges: ['new'], ageDays: 2 }),
    lot({ title: '30x Alo / Vuori / Gymshark Mix — Stated Counts', section: 14, subcategories: ['Sports Bras / Longline Sports Bras', 'Performance / Training Joggers'], styles: [SP], brands: [['Alo', 10], ['Vuori', 10], ['Gymshark', 10]], descriptors: [['Use', 'Gym / Training']], bestFor: ['Activewear specialists', 'Branded resale stores'], lotType: 'mixed-brand', pieces: 30, weightKg: 6, grade: 'a', division: ['womens', 'mens'], price: 540, unit: 'lot', priceVisibility: 'public', lotsAvailable: 4, stock: 'in-stock', badges: [], ageDays: 11 }),
    lot({ title: '20x Coach Vintage Leather Shoulder Bags', section: 15, subcategories: ['Classic Shoulder / Flap Bags'], styles: [CP, YV], brands: [['Coach', 20]], collection: 'Coach Vintage / Heritage Leather', descriptors: [['Material', 'Leather'], ['Size', 'Medium'], ['Production', 'Original Production']], bestFor: ['Coach specialists', 'Vintage leather sellers'], lotType: 'single-brand', pieces: 20, weightKg: 12, grade: 'a', era: 'verified-vintage', division: ['womens'], price: 1380, unit: 'lot', priceVisibility: 'trade-only', lotsAvailable: 2, stock: 'low', badges: ['verified-era'], ageDays: 5 }),
    lot({ title: '25x George Gina & Lucy Utility Bags', section: 15, subcategories: ['Multi-Pocket / Cargo / Utility Bags'], styles: [YV], brands: [['George Gina & Lucy', 25]], collection: 'GG&L Signature Multi-Pocket / Utility', descriptors: [['Material', 'Nylon']], bestFor: ['Y2K resellers', 'GG&L specialists'], lotType: 'single-brand', pieces: 25, weightKg: 10, grade: 'a', era: 'verified-y2k', division: ['womens'], price: 690, unit: 'lot', priceVisibility: 'public', lotsAvailable: 3, stock: 'in-stock', badges: [], ageDays: 14 }),
    lot({ title: '30x Vintage Guess & Kathy Van Zeeland McBling Bags', section: 15, subcategories: ['Baguette / East–West Shoulder Bags', 'Hobo / Slouch / Crescent Bags'], styles: [YV], brands: [['Vintage Guess', 15], ['Kathy Van Zeeland', 15]], descriptors: [['Detail', 'Rhinestones'], ['Detail', 'Charms'], ['Detail', 'Metallic']], bestFor: ['Y2K & McBling resellers', 'Y2K boutiques'], lotType: 'mixed-brand', pieces: 30, weightKg: 11, grade: 'a', era: 'verified-y2k', division: ['womens'], price: 640, unit: 'lot', priceVisibility: 'public', lotsAvailable: 4, stock: 'in-stock', badges: ['new'], ageDays: 2 }),
    lot({ title: '40x Shoulder Bags — Shape-Specific, Unbranded Y2K Style', section: 15, subcategories: ['Classic Shoulder / Flap Bags'], styles: [YV], brands: [['Unbranded Y2K', 40]], descriptors: [['Size', 'Small']], bestFor: ['Budget-fashion sellers', 'Style-led resellers'], lotType: 'shape-specific', pieces: 40, weightKg: 10, grade: 'b', era: 'y2k-style', division: ['womens'], price: 260, unit: 'lot', priceVisibility: 'public', lotsAvailable: 8, stock: 'arriving', badges: [], ageDays: 0 }),
  ]
}
