/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    customers: CustomerAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    lots: Lot;
    sections: Section;
    subcategories: Subcategory;
    brands: Brand;
    'brand-collections': BrandCollection;
    'fashion-categories': FashionCategory;
    descriptors: Descriptor;
    'buyer-types': BuyerType;
    quotes: Quote;
    customers: Customer;
    'price-lists': PriceList;
    pages: Page;
    reviews: Review;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    lots: LotsSelect<false> | LotsSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'brand-collections': BrandCollectionsSelect<false> | BrandCollectionsSelect<true>;
    'fashion-categories': FashionCategoriesSelect<false> | FashionCategoriesSelect<true>;
    descriptors: DescriptorsSelect<false> | DescriptorsSelect<true>;
    'buyer-types': BuyerTypesSelect<false> | BuyerTypesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'price-lists': PriceListsSelect<false> | PriceListsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Customer | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lots".
 */
export interface Lot {
  id: number;
  title: string;
  sku: string;
  lotType: 'single-brand' | 'mixed-brand' | 'bale-kg' | 'shape-specific' | 'on-request';
  pieces?: number | null;
  weightKg?: number | null;
  grade: 'cream' | 'a' | 'b' | 'mixed';
  era?: ('verified-vintage' | '1980s' | '1990s' | 'verified-y2k' | 'y2k-style' | 'modern') | null;
  division?: ('womens' | 'mens' | 'unisex')[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Your own stock photos only, 4:5, ≥ 1600 px. Name files SKU_01.jpg.
   */
  media?:
    | {
        image: number | Media;
        alt: string;
        kind?: ('image' | 'video') | null;
        id?: string | null;
      }[]
    | null;
  section: number | Section;
  subcategory?: (number | Subcategory)[] | null;
  fashionCategories?: (number | FashionCategory)[] | null;
  /**
   * Mix breakdown. Counts feed the MixBreakdownChart.
   */
  brands?:
    | {
        brand: number | Brand;
        count?: number | null;
        id?: string | null;
      }[]
    | null;
  brandCollection?: (number | null) | BrandCollection;
  descriptors?: (number | Descriptor)[] | null;
  designGroups?: (number | Descriptor)[] | null;
  bestSuitedFor?: (number | BuyerType)[] | null;
  priceVisibility: 'public' | 'trade-only' | 'on-request';
  /**
   * Guide prices excl. VAT & shipping. Bands must start at 1 and follow on (e.g. 1 / 2–4 / 5–9 / 10+). Leave max empty on the last band.
   */
  priceTiers: {
    minQty: number;
    maxQty?: number | null;
    /**
     * £ per unit
     */
    price?: number | null;
    unit: 'lot' | 'kg' | 'piece';
    quoteOnly?: boolean | null;
    id?: string | null;
  }[];
  stock: {
    lotsAvailable: number;
    /**
     * Soft-reserved by open RFQs (48 h).
     */
    reserved?: number | null;
    status: 'in-stock' | 'low' | 'arriving' | 'reserved' | 'sold';
    dispatch?: string | null;
    moq?: number | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Used in the URL. Leave blank to generate from the title.
   */
  slug: string;
  status: 'draft' | 'published' | 'archived';
  badges?: ('new' | 'best-seller' | 'verified-era')[] | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the photo shows (used as alt text).
   */
  alt: string;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  number: number;
  name: string;
  /**
   * Used in the URL. Leave blank to generate from the name.
   */
  slug: string;
  /**
   * 1–2 lines shown under the H1.
   */
  intro?: string | null;
  /**
   * 3:4 tile image.
   */
  image?: (number | null) | Media;
  menuColumn?: ('1' | '2') | null;
  /**
   * Group headings, e.g. "A — Lightweight / Technical / Shell".
   */
  subcategoryGroups?:
    | {
        /**
         * A, B, C…
         */
        key: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Expandable text at the bottom of the listing.
   */
  seoContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: number;
  name: string;
  /**
   * Unique within its section, e.g. /shop/jackets/windbreakers.
   */
  slug: string;
  section: number | Section;
  /**
   * Group key from the section (A, B, C…).
   */
  group?: string | null;
  intro?: string | null;
  image?: (number | null) | Media;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fashion-categories".
 */
export interface FashionCategory {
  id: number;
  name: string;
  /**
   * Used in the URL. Leave blank to generate from the name.
   */
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * Used in the URL. Leave blank to generate from the name.
   */
  slug: string;
  /**
   * Short, neutral description. No brand marketing copy.
   */
  description?: string | null;
  /**
   * Leave blank for the standard "Independent reseller — not affiliated with [Brand]" note.
   */
  disclaimer?: string | null;
  fashionCategories?: (number | FashionCategory)[] | null;
  /**
   * Monochrome SVG, named brand-[slug].svg.
   */
  logoSvg?: (number | null) | Media;
  logoApproved?: boolean | null;
  /**
   * Always show a text wordmark, even if approved.
   */
  wordmarkOnly?: boolean | null;
  /**
   * Show in the Brands mega menu (top 16).
   */
  featured?: boolean | null;
  /**
   * Sourced on request (e.g. Dior, Gucci, Louis Vuitton).
   */
  luxuryOnRequest?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-collections".
 */
export interface BrandCollection {
  id: number;
  name: string;
  /**
   * Used in the URL. Leave blank to generate from the name.
   */
  slug: string;
  brand: number | Brand;
  section?: (number | null) | Section;
  /**
   * Badge label, e.g. "A. Premium / Iconic".
   */
  tier?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "descriptors".
 */
export interface Descriptor {
  id: number;
  term: string;
  /**
   * Used in the URL. Leave blank to generate from the term.
   */
  slug: string;
  kind: 'descriptor' | 'design-group';
  /**
   * Facet heading, e.g. "Fill power".
   */
  group: string;
  /**
   * Only show this facet on these sections. Leave empty for all.
   */
  sections?: (number | Section)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyer-types".
 */
export interface BuyerType {
  id: number;
  name: string;
  /**
   * Used in the URL. Leave blank to generate from the name.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  /**
   * QR-YYYY-####, set automatically.
   */
  ref?: string | null;
  status: 'submitted' | 'quoted' | 'revised' | 'accepted' | 'invoiced' | 'dispatched' | 'expired' | 'closed';
  customer?: (number | null) | Customer;
  /**
   * Snapshot of the basket at submission.
   */
  lines: {
    lot: number | Lot;
    qty: number;
    title: string;
    sku: string;
    /**
     * Empty = quote only.
     */
    guideSubtotalPence?: number | null;
    quotedSubtotalPence?: number | null;
    id?: string | null;
  }[];
  notes?: string | null;
  details: {
    company: string;
    contactName: string;
    email: string;
    phone?: string | null;
    vatNumber?: string | null;
    country: string;
    postcode?: string | null;
    shippingMethod?: ('collect' | 'uk-courier' | 'pallet' | 'international') | null;
    paymentPreference?: ('bank-transfer' | 'card-link') | null;
    deadline?: string | null;
  };
  internalNotes?: string | null;
  quotePdf?: (number | null) | Media;
  reservedUntil?: string | null;
  quotedAt?: string | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  company: string;
  contactName: string;
  phone?: string | null;
  vatNumber?: string | null;
  companyNumber?: string | null;
  country: string;
  buyerType?: (number | null) | BuyerType;
  tradeStatus?: ('none' | 'pending' | 'approved' | 'rejected') | null;
  /**
   * Overrides guide prices when logged in.
   */
  priceList?: (number | null) | PriceList;
  addresses?:
    | {
        label?: string | null;
        line1: string;
        line2?: string | null;
        city: string;
        postcode: string;
        country: string;
        id?: string | null;
      }[]
    | null;
  savedLots?: (number | Lot)[] | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-lists".
 */
export interface PriceList {
  id: number;
  name: string;
  /**
   * % off every guide price.
   */
  discountPercent?: number | null;
  /**
   * Exact bands for specific lots. These win over the discount.
   */
  overrides?:
    | {
        lot: number | Lot;
        /**
         * Guide prices excl. VAT & shipping. Bands must start at 1 and follow on (e.g. 1 / 2–4 / 5–9 / 10+). Leave max empty on the last band.
         */
        priceTiers?:
          | {
              minQty: number;
              maxQty?: number | null;
              /**
               * £ per unit
               */
              price?: number | null;
              unit: 'lot' | 'kg' | 'piece';
              quoteOnly?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Used in the URL. Leave blank to generate from the title.
   */
  slug: string;
  intro?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  author: string;
  rating: number;
  body: string;
  source: 'google' | 'trustpilot' | 'other';
  sourceUrl: string;
  date: string;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'lots';
        value: number | Lot;
      } | null)
    | ({
        relationTo: 'sections';
        value: number | Section;
      } | null)
    | ({
        relationTo: 'subcategories';
        value: number | Subcategory;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'brand-collections';
        value: number | BrandCollection;
      } | null)
    | ({
        relationTo: 'fashion-categories';
        value: number | FashionCategory;
      } | null)
    | ({
        relationTo: 'descriptors';
        value: number | Descriptor;
      } | null)
    | ({
        relationTo: 'buyer-types';
        value: number | BuyerType;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'price-lists';
        value: number | PriceList;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lots_select".
 */
export interface LotsSelect<T extends boolean = true> {
  title?: T;
  sku?: T;
  lotType?: T;
  pieces?: T;
  weightKg?: T;
  grade?: T;
  era?: T;
  division?: T;
  description?: T;
  media?:
    | T
    | {
        image?: T;
        alt?: T;
        kind?: T;
        id?: T;
      };
  section?: T;
  subcategory?: T;
  fashionCategories?: T;
  brands?:
    | T
    | {
        brand?: T;
        count?: T;
        id?: T;
      };
  brandCollection?: T;
  descriptors?: T;
  designGroups?: T;
  bestSuitedFor?: T;
  priceVisibility?: T;
  priceTiers?:
    | T
    | {
        minQty?: T;
        maxQty?: T;
        price?: T;
        unit?: T;
        quoteOnly?: T;
        id?: T;
      };
  stock?:
    | T
    | {
        lotsAvailable?: T;
        reserved?: T;
        status?: T;
        dispatch?: T;
        moq?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  slug?: T;
  status?: T;
  badges?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  number?: T;
  name?: T;
  slug?: T;
  intro?: T;
  image?: T;
  menuColumn?: T;
  subcategoryGroups?:
    | T
    | {
        key?: T;
        label?: T;
        id?: T;
      };
  seoContent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  section?: T;
  group?: T;
  intro?: T;
  image?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  disclaimer?: T;
  fashionCategories?: T;
  logoSvg?: T;
  logoApproved?: T;
  wordmarkOnly?: T;
  featured?: T;
  luxuryOnRequest?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-collections_select".
 */
export interface BrandCollectionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  brand?: T;
  section?: T;
  tier?: T;
  description?: T;
  image?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fashion-categories_select".
 */
export interface FashionCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "descriptors_select".
 */
export interface DescriptorsSelect<T extends boolean = true> {
  term?: T;
  slug?: T;
  kind?: T;
  group?: T;
  sections?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buyer-types_select".
 */
export interface BuyerTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  ref?: T;
  status?: T;
  customer?: T;
  lines?:
    | T
    | {
        lot?: T;
        qty?: T;
        title?: T;
        sku?: T;
        guideSubtotalPence?: T;
        quotedSubtotalPence?: T;
        id?: T;
      };
  notes?: T;
  details?:
    | T
    | {
        company?: T;
        contactName?: T;
        email?: T;
        phone?: T;
        vatNumber?: T;
        country?: T;
        postcode?: T;
        shippingMethod?: T;
        paymentPreference?: T;
        deadline?: T;
      };
  internalNotes?: T;
  quotePdf?: T;
  reservedUntil?: T;
  quotedAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  company?: T;
  contactName?: T;
  phone?: T;
  vatNumber?: T;
  companyNumber?: T;
  country?: T;
  buyerType?: T;
  tradeStatus?: T;
  priceList?: T;
  addresses?:
    | T
    | {
        label?: T;
        line1?: T;
        line2?: T;
        city?: T;
        postcode?: T;
        country?: T;
        id?: T;
      };
  savedLots?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-lists_select".
 */
export interface PriceListsSelect<T extends boolean = true> {
  name?: T;
  discountPercent?: T;
  overrides?:
    | T
    | {
        lot?: T;
        priceTiers?:
          | T
          | {
              minQty?: T;
              maxQty?: T;
              price?: T;
              unit?: T;
              quoteOnly?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  intro?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  author?: T;
  rating?: T;
  body?: T;
  source?: T;
  sourceUrl?: T;
  date?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Keep OFF until you have written permission or UK IP-solicitor sign-off. When off, every brand shows as a text wordmark. Each brand also needs "Logo approved".
   */
  showBrandLogos?: boolean | null;
  /**
   * Hide all guide prices from guests (trade-only lots are always hidden).
   */
  requireLoginForPrices?: boolean | null;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    /**
     * International format, e.g. 447700900000.
     */
    whatsapp?: string | null;
    address?: string | null;
  };
  /**
   * Short, provable facts only.
   */
  trust?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  showBrandLogos?: T;
  requireLoginForPrices?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
        address?: T;
      };
  trust?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}